In [52]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression

заменим лекционный датасет на условные ср чек, кол чеков, трафик и производная первых двух - выручка
и возьмем 5000 записей

In [53]:
# Создаём сэмпл
n_samples = 5000

sr_4ek = np.random.choice(3000, n_samples) + 21
kol_4ek = np.random.choice(200, n_samples) + 15
traffic = np.random.choice(600, n_samples) + 45

sum_rub = sr_4ek * kol_4ek * 1

data = pd.DataFrame({'sr_4ek': sr_4ek, 'kol_4ek': kol_4ek, 'traffic': traffic, 'sum_rub': sum_rub})
data.head(5)

sr_4ek  kol_4ek  traffic  sum_rub
0      47      195      277     9165
1    1042      124       57   129208
2     494      175      223    86450
3    2070      127      525   262890
4    2447       91      256   222677

построим лин регрессию выручки со всеми показателями

In [54]:
from sklearn.metrics import mean_absolute_error

X = data[['sr_4ek', 'kol_4ek', 'traffic']]
y = data['sum_rub']
reg = LinearRegression().fit(X, y)
print('Weights: {}'.format(reg.coef_))
print('Bias: {}'.format(reg.intercept_))

pred_values = reg.predict(data[['sr_4ek', 'kol_4ek', 'traffic']])
print('Error: {}'.format(mean_absolute_error(pred_values, y)))

Weights: [1.16669696e+02 1.49918750e+03 1.02800895e+00]
Bias: -174208.64642847396
Error: 36183.27670298136


получаем значительную ошибку

рассмотрим лин регрессию выручки со ср чеком и кол чеков

In [55]:
X = data[['sr_4ek', 'kol_4ek']]
y = data['sum_rub']
reg = LinearRegression().fit(X, y)
print('Weights: {}'.format(reg.coef_))
print('Bias: {}'.format(reg.intercept_))

pred_values = reg.predict(data[['sr_4ek', 'kol_4ek']])
print('Error: {}'.format(mean_absolute_error(pred_values, y)))

Weights: [ 116.66957381 1499.21061956]
Bias: -173852.01117639305
Error: 36187.21793659117


честно говоря не очень понимаю почему ошибка по прежнему значительна ведь выручка я вляется произведением этих показателей(

In [56]:
(pred_values)

array([123977.52960613, 133619.80155486, 146144.61670641, ...,
       230991.67377736, 306786.91330345, 249128.20308295])

создадим новый производный признак второй показатель выручки как произведение ср чека на кол чеков вычисленное как произведение вх трафика на условную конверсию в 30%

In [57]:
# Создаем новый признак
data['sum2'] = data['sr_4ek'] * data['traffic']*30/100
data.head(5)

sr_4ek  kol_4ek  traffic  sum_rub      sum2
0      47      195      277     9165    3905.7
1    1042      124       57   129208   17818.2
2     494      175      223    86450   33048.6
3    2070      127      525   262890  326025.0
4    2447       91      256   222677  187929.6

In [58]:
len(data)

5000

построим лин регрессию выручки с вх трафиком

In [59]:
X = data[['sum2']]
y = data['traffic']
reg = LinearRegression().fit(X, y)
print('Weights: {}'.format(reg.coef_))
print('Bias: {}'.format(reg.intercept_))

pred_values = reg.predict(data[['sum2']])
print('Error: {}'.format(mean_absolute_error(pred_values, y)))

Weights: [0.0008415]
Bias: 216.2774290660933
Error: 112.6008207346993


получаем  лин регрессию двух показателей с минимальной ошибкой относительно ср значения выручки

In [60]:
data['sum2'].head()

0      3905.7
1     17818.2
2     33048.6
3    326025.0
4    187929.6
Name: sum2, dtype: float64

In [61]:
print(traffic)
(pred_values)


[277  57 223 ... 118 299 552]


array([219.56408227, 231.27147471, 244.08788225, ..., 304.33418688,
       363.31773406, 583.6110989 ])

вот здесь я не очень понимаю, почему предсказанные значения выручки значительно отличаются от исходных

In [11]:
len(pred_values)


5000

In [12]:
reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)